packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

onlyBuiltDependencies:
  - msgpackr-extract

catalog:
  "@effect/platform-browser": 4.0.0-beta.70
  "@effect/platform-node": 4.0.0-beta.70
  "@effect/language-service": 0.86.2
  "@effect/vitest": 4.0.0-beta.70
  "@types/node": 25.9.1
  "@vitest/coverage-istanbul": 4.1.6
  "@vitest/runner": 4.1.6
  effect: 4.0.0-beta.70
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.1.23
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.23
  vite-plus: 0.1.23
  "@effect/atom-react": 4.0.0-beta.70
  scheduler: 0.27.0
  vitest-browser-react: 2.2.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  msgpackr-extract: true
