packages:
  - apps/*
  - examples/*
  - packages/*
  - tools/*

catalogMode: prefer

onlyBuiltDependencies:
  - msgpackr-extract

catalog:
  "@effect/platform-browser": 4.0.0-beta.91
  "@effect/platform-node": 4.0.0-beta.91
  "@effect/language-service": 0.86.2
  "@effect/vitest": 4.0.0-beta.91
  "@types/node": 25.9.1
  "@vitest/browser": 4.1.9
  "@vitest/browser-playwright": 4.1.9
  "@vitest/coverage-istanbul": 4.1.9
  "@vitest/runner": 4.1.9
  effect: 4.0.0-beta.91
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vitest: 4.1.9
  vite-plus: 0.2.1
  "@effect/atom-react": 4.0.0-beta.91
  scheduler: 0.27.0
  vitest-browser-react: 2.2.0
  "@platformatic/kafka": 2.2.3
  "@connectrpc/connect": 2.1.2
  "@connectrpc/connect-node": 2.1.2
  "@tailwindcss/vite": 4.3.1
  "@tanstack/react-router": 1.170.16
  "@tanstack/react-start": 1.168.26
  "@tanstack/router-cli": 1.167.17
  "@tanstack/router-plugin": 1.168.18
  "@vitejs/plugin-react": 6.0.3
  tailwindcss: 4.3.1
  tsx: 4.22.4
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - "@effect/atom-react@4.0.0-beta.91"
  - "@effect/platform-browser@4.0.0-beta.91"
  - "@effect/platform-node-shared@4.0.0-beta.91"
  - "@effect/platform-node@4.0.0-beta.91"
  - "@effect/vitest@4.0.0-beta.91"
  - effect@4.0.0-beta.91
